// Automatically generated by astro-icon
// 67b417b1d3fbc25b782dd442df0d0b467a0b5265829e9663aa366dc03c7e7121

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "envelope-solid-full"
		| "github-brands-solid"
		| "linkedin-brands-solid";
}